import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./_components/Menu/Menu";
import CV_BG from "../../public/images/CV_BG.jpg";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}  container mt-10  `}>
        <div className="absolute max-w-[1200px]  z-0">
          <Image
            className="aspect-[1100/700]"
            src={CV_BG}
            alt={CV_BG.src}
            objectFit="cover"
          />
        </div>
        <div className="CONTENT z-20 relative flex flex-row justify-between pt-10">
          <div className="w-3/12 bg-red-500 text-red-200">Info</div>
          <div className="w-8/12 ">
            <div>
              <Menu />
            </div>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
